// Email Catalog - Central registry of all automated system emails
// This is a view-only reference for the admin portal

export type EmailCategory = 'lifecycle' | 'engagement' | 'team' | 'admin' | 'campaign' | 'seasonal';
export type EmailFrequency = 'one-time' | 'daily' | 'weekly' | 'event-based' | 'annual';

export interface EmailDefinition {
  id: string;
  name: string;
  category: EmailCategory;
  trigger: string;
  edgeFunctionName: string;
  isPersonalized: boolean;
  subjectTemplate: string;
  description: string;
  frequency: EmailFrequency;
  fromAddress: string;
}

export const emailCatalog: EmailDefinition[] = [
  // ============ LIFECYCLE EMAILS ============
  {
    id: 'welcome',
    name: 'Welcome Email',
    category: 'lifecycle',
    trigger: 'User completes signup',
    edgeFunctionName: 'send-welcome-email',
    isPersonalized: true,
    subjectTemplate: 'Welcome to Mind & Muscle, {{firstName}}! 🎯',
    description: 'Sent immediately after a new user signs up. Introduces the app and key features.',
    frequency: 'one-time',
    fromAddress: 'hello@mindandmuscle.ai',
  },
  {
    id: 'trial-gift',
    name: 'Trial Gift Email',
    category: 'lifecycle',
    trigger: 'Trial subscription granted',
    edgeFunctionName: 'send-trial-gift-email',
    isPersonalized: true,
    subjectTemplate: '🎁 {{firstName}}, your Pro trial is ready!',
    description: 'Notifies users when they receive a free trial of Pro features.',
    frequency: 'one-time',
    fromAddress: 'hello@mindandmuscle.ai',
  },
  {
    id: 'user-lifecycle',
    name: 'User Lifecycle Email',
    category: 'lifecycle',
    trigger: 'Various lifecycle milestones (Day 3, Day 7, etc.)',
    edgeFunctionName: 'send-user-lifecycle-email',
    isPersonalized: true,
    subjectTemplate: 'Dynamic based on lifecycle stage',
    description: 'Automated drip campaign based on user lifecycle stage. Encourages engagement at key moments.',
    frequency: 'event-based',
    fromAddress: 'hello@mindandmuscle.ai',
  },
  {
    id: 'winback',
    name: 'Winback Campaign',
    category: 'lifecycle',
    trigger: 'User inactive for 14+ days',
    edgeFunctionName: 'send-winback-campaign',
    isPersonalized: true,
    subjectTemplate: '{{firstName}}, we miss you! Come back to training 💪',
    description: 'Re-engagement email for churned or inactive users. Highlights new features and value.',
    frequency: 'event-based',
    fromAddress: 'hello@mindandmuscle.ai',
  },
  {
    id: 'marketing-trial',
    name: 'Marketing Trial Email',
    category: 'lifecycle',
    trigger: 'Marketing promotion or campaign',
    edgeFunctionName: 'send-marketing-trial-email',
    isPersonalized: true,
    subjectTemplate: '{{firstName}}, unlock Pro for free this week!',
    description: 'Promotional email offering trial access during marketing campaigns.',
    frequency: 'event-based',
    fromAddress: 'hello@mindandmuscle.ai',
  },
  {
    id: 'trial-expiration',
    name: 'Trial Expiration Notice',
    category: 'lifecycle',
    trigger: 'Trial ending in 3 days / expired',
    edgeFunctionName: 'trial-expiration-checker',
    isPersonalized: true,
    subjectTemplate: '{{firstName}}, your Pro trial expires soon!',
    description: 'Warns users their trial is ending and encourages conversion to paid.',
    frequency: 'event-based',
    fromAddress: 'hello@mindandmuscle.ai',
  },

  // ============ ENGAGEMENT EMAILS ============
  {
    id: 'daily-hit-followup',
    name: 'Daily Hit Followup',
    category: 'engagement',
    trigger: 'User completes Daily Hit session',
    edgeFunctionName: 'send-daily-hit-followup',
    isPersonalized: true,
    subjectTemplate: 'Great job, {{firstName}}! You crushed today\'s Daily Hit 🎯',
    description: 'Congratulates users after completing Daily Hit. Encourages reflection in Dugout Talk.',
    frequency: 'event-based',
    fromAddress: 'support@mindandmuscle.ai',
  },
  {
    id: 'daily-hit-website',
    name: 'Daily Hit (Website Subscribers)',
    category: 'engagement',
    trigger: 'Daily cron job at 8 AM Central',
    edgeFunctionName: 'send-daily-hit-website',
    isPersonalized: true,
    subjectTemplate: '{{firstName}}, your Daily Hit is ready! 🎯',
    description: 'Sends daily motivation content to website email subscribers (non-app users).',
    frequency: 'daily',
    fromAddress: 'support@mindandmuscle.ai',
  },
  {
    id: 'content-reflection',
    name: 'Content Reflection Email',
    category: 'engagement',
    trigger: 'After completing media content',
    edgeFunctionName: 'send_content_reflection_email',
    isPersonalized: true,
    subjectTemplate: '{{firstName}}, reflect on today\'s session: {{contentTitle}}',
    description: 'Prompts users to reflect on completed content in Dugout Talk.',
    frequency: 'event-based',
    fromAddress: 'support@mindandmuscle.ai',
  },
  {
    id: 'streak-milestone',
    name: 'Streak Milestone Email',
    category: 'engagement',
    trigger: 'User reaches 1, 7, 14, 30, 100 day streak',
    edgeFunctionName: 'send-streak-milestone-email',
    isPersonalized: true,
    subjectTemplate: '🔥 {{firstName}}, you hit a {{streakDays}}-day streak!',
    description: 'Celebrates user streaks at key milestones. Reinforces habit building.',
    frequency: 'event-based',
    fromAddress: 'hello@mindandmuscle.ai',
  },
  {
    id: 'feature-spotlight',
    name: 'Weekly Feature Spotlight',
    category: 'engagement',
    trigger: 'Weekly cron job',
    edgeFunctionName: 'weekly-feature-spotlight-cron',
    isPersonalized: true,
    subjectTemplate: '✨ {{firstName}}, discover this week\'s featured content',
    description: 'Weekly email highlighting features users may not have discovered.',
    frequency: 'weekly',
    fromAddress: 'hello@mindandmuscle.ai',
  },
  {
    id: 'comeback-notification',
    name: 'Comeback Notification',
    category: 'engagement',
    trigger: 'User returns after inactivity',
    edgeFunctionName: 'comeback-notification',
    isPersonalized: true,
    subjectTemplate: 'Welcome back, {{firstName}}! 🎉',
    description: 'Welcomes users back after a period of inactivity.',
    frequency: 'event-based',
    fromAddress: 'hello@mindandmuscle.ai',
  },
  {
    id: 'weekly-athlete-digest',
    name: 'Weekly Athlete Digest',
    category: 'engagement',
    trigger: 'Sunday 6pm Central (weekly cron)',
    edgeFunctionName: 'send-weekly-athlete-digest',
    isPersonalized: true,
    subjectTemplate: 'Your Week in Review, {{firstName}}! 📊',
    description: 'Weekly training recap for active athletes. Shows sessions completed, streak status, and encouragement.',
    frequency: 'weekly',
    fromAddress: 'hello@mindandmuscle.ai',
  },
  {
    id: 'pre-churn-nudge',
    name: 'Pre-Churn Nudge',
    category: 'engagement',
    trigger: 'User inactive for 3-5 days (before 7-day reengagement)',
    edgeFunctionName: 'send-pre-churn-nudge',
    isPersonalized: true,
    subjectTemplate: 'Don\'t lose your {{streak}}-day streak! 🔥',
    description: 'Early intervention for users showing signs of churn. Personalized to their last feature used.',
    frequency: 'daily',
    fromAddress: 'hello@mindandmuscle.ai',
  },
  {
    id: 'achievement-celebration',
    name: 'Achievement Celebration',
    category: 'engagement',
    trigger: 'User reaches milestone (10/25/50/100 analyses, streaks, etc.)',
    edgeFunctionName: 'send-achievement-celebration',
    isPersonalized: true,
    subjectTemplate: '{{emoji}} {{achievementTitle}} - You Earned It!',
    description: 'Celebrates user achievements with shareable content and referral CTA.',
    frequency: 'event-based',
    fromAddress: 'hello@mindandmuscle.ai',
  },

  // ============ TEAM/COACH EMAILS ============
  {
    id: 'coach-attendance-daily',
    name: 'Coach Attendance Daily Digest',
    category: 'team',
    trigger: 'Daily summary of team attendance',
    edgeFunctionName: 'coach-attendance-daily-digest',
    isPersonalized: true,
    subjectTemplate: 'Daily Attendance: {{teamName}} - {{date}}',
    description: 'Daily summary of team member attendance for coaches.',
    frequency: 'daily',
    fromAddress: 'support@mindandmuscle.ai',
  },
  {
    id: 'coach-attendance-weekly',
    name: 'Coach Attendance Weekly Digest',
    category: 'team',
    trigger: 'Weekly team attendance summary',
    edgeFunctionName: 'coach-attendance-weekly-digest',
    isPersonalized: true,
    subjectTemplate: 'Weekly Attendance Report: {{teamName}}',
    description: 'Weekly rollup of team attendance and engagement for coaches.',
    frequency: 'weekly',
    fromAddress: 'support@mindandmuscle.ai',
  },
  {
    id: 'new-event-notification',
    name: 'New Event Notification',
    category: 'team',
    trigger: 'Coach creates team event',
    edgeFunctionName: 'new-event-notifications',
    isPersonalized: true,
    subjectTemplate: '📅 New event: {{eventName}} - {{teamName}}',
    description: 'Notifies team members when coach creates a new event.',
    frequency: 'event-based',
    fromAddress: 'support@mindandmuscle.ai',
  },
  {
    id: 'attendance-notifications',
    name: 'Attendance Notifications',
    category: 'team',
    trigger: 'Event attendance changes',
    edgeFunctionName: 'attendance-notifications',
    isPersonalized: true,
    subjectTemplate: 'Attendance update for {{eventName}}',
    description: 'Notifies relevant parties of attendance status changes.',
    frequency: 'event-based',
    fromAddress: 'support@mindandmuscle.ai',
  },
  {
    id: 'coach-feedback-notification',
    name: 'Coach Feedback Notification',
    category: 'team',
    trigger: 'Coach leaves feedback on analysis',
    edgeFunctionName: 'coach-feedback-notification',
    isPersonalized: true,
    subjectTemplate: '💬 Coach feedback on your {{analysisType}}',
    description: 'Notifies athlete when coach leaves feedback on their Swing/Pitch Lab analysis.',
    frequency: 'event-based',
    fromAddress: 'support@mindandmuscle.ai',
  },
  {
    id: 'drill-assignment-notification',
    name: 'Drill Assignment Notification',
    category: 'team',
    trigger: 'Coach assigns drill to athlete',
    edgeFunctionName: 'drill-assignment-notification',
    isPersonalized: true,
    subjectTemplate: '🎯 New drill assigned: {{drillName}}',
    description: 'Notifies athlete when coach assigns them a drill from The Vault.',
    frequency: 'event-based',
    fromAddress: 'support@mindandmuscle.ai',
  },
  {
    id: 'parent-weekly-report',
    name: 'Parent Weekly Report',
    category: 'team',
    trigger: 'Monday 8am Central (weekly cron)',
    edgeFunctionName: 'send-parent-weekly-report',
    isPersonalized: true,
    subjectTemplate: '{{athleteName}}\'s Weekly Training Report 📊',
    description: 'Weekly training summary for parents with linked athletes. Shows activity, streaks, and tips.',
    frequency: 'weekly',
    fromAddress: 'hello@mindandmuscle.ai',
  },

  // ============ ADMIN/SYSTEM EMAILS ============
  {
    id: 'parental-consent',
    name: 'Parental Consent Email',
    category: 'admin',
    trigger: 'Minor athlete signs up',
    edgeFunctionName: 'send-parental-consent-email',
    isPersonalized: true,
    subjectTemplate: 'Parental consent required for {{athleteName}}',
    description: 'Requests parental consent for athletes under 13.',
    frequency: 'one-time',
    fromAddress: 'support@mindandmuscle.ai',
  },
  {
    id: 'support-email',
    name: 'Support Email',
    category: 'admin',
    trigger: 'User submits support request',
    edgeFunctionName: 'send-support-email',
    isPersonalized: true,
    subjectTemplate: 'Support Request: {{subject}}',
    description: 'Forwards support requests to the support team.',
    frequency: 'event-based',
    fromAddress: 'support@mindandmuscle.ai',
  },
  {
    id: 'admin-alert',
    name: 'Admin Alert Email',
    category: 'admin',
    trigger: 'System alert or error',
    edgeFunctionName: 'send-admin-alert-email',
    isPersonalized: false,
    subjectTemplate: '⚠️ Admin Alert: {{alertType}}',
    description: 'Sends critical system alerts to admin team.',
    frequency: 'event-based',
    fromAddress: 'alerts@mindandmuscle.ai',
  },
  {
    id: 'password-reset',
    name: 'Password Reset Email',
    category: 'admin',
    trigger: 'User requests password reset',
    edgeFunctionName: 'request-password-reset',
    isPersonalized: true,
    subjectTemplate: 'Reset your Mind & Muscle password',
    description: 'Sends password reset link to user.',
    frequency: 'event-based',
    fromAddress: 'support@mindandmuscle.ai',
  },
  {
    id: 'parent-link-notification',
    name: 'Parent Link Notification',
    category: 'admin',
    trigger: 'Athlete links to parent account',
    edgeFunctionName: 'parent_link_notification',
    isPersonalized: true,
    subjectTemplate: '👨‍👧 {{athleteName}} wants to link with you',
    description: 'Notifies parent when athlete requests account linkage.',
    frequency: 'event-based',
    fromAddress: 'support@mindandmuscle.ai',
  },

  // ============ CAMPAIGN EMAILS ============
  {
    id: 'campaign-email',
    name: 'Campaign Email',
    category: 'campaign',
    trigger: 'Manual outreach campaign',
    edgeFunctionName: 'send-campaign-email',
    isPersonalized: true,
    subjectTemplate: 'Dynamic based on campaign template',
    description: 'Sends marketing campaign emails to leads and prospects.',
    frequency: 'event-based',
    fromAddress: 'partnerships@mindandmuscle.ai',
  },
  {
    id: 'test-campaign',
    name: 'Test Campaign Email',
    category: 'campaign',
    trigger: 'Testing campaign templates',
    edgeFunctionName: 'send-test-campaign-email',
    isPersonalized: true,
    subjectTemplate: '[TEST] Campaign preview',
    description: 'Sends test version of campaign emails for preview.',
    frequency: 'event-based',
    fromAddress: 'partnerships@mindandmuscle.ai',
  },
  {
    id: 'partner-payment-reminder',
    name: 'Partner Payment Reminder',
    category: 'campaign',
    trigger: 'Partner commission due',
    edgeFunctionName: 'partner-payment-reminder',
    isPersonalized: true,
    subjectTemplate: '💰 Commission payment reminder',
    description: 'Reminds partners about pending commission payments.',
    frequency: 'event-based',
    fromAddress: 'partnerships@mindandmuscle.ai',
  },

  // ============ SEASONAL EMAILS ============
  {
    id: 'happy-new-year',
    name: 'Happy New Year Email',
    category: 'seasonal',
    trigger: 'January 1st (manual)',
    edgeFunctionName: 'send-happy-new-year-email',
    isPersonalized: true,
    subjectTemplate: '🎉 Happy New Year, {{firstName}}!',
    description: 'Annual New Year greeting with upcoming features preview.',
    frequency: 'annual',
    fromAddress: 'hello@mindandmuscle.ai',
  },
];

// Category display names and colors
export const categoryConfig: Record<EmailCategory, { label: string; color: string; bgColor: string }> = {
  lifecycle: { label: 'Lifecycle', color: 'text-blue-700', bgColor: 'bg-blue-100' },
  engagement: { label: 'Engagement', color: 'text-green-700', bgColor: 'bg-green-100' },
  team: { label: 'Team/Coach', color: 'text-purple-700', bgColor: 'bg-purple-100' },
  admin: { label: 'Admin', color: 'text-gray-700', bgColor: 'bg-gray-100' },
  campaign: { label: 'Campaign', color: 'text-orange-700', bgColor: 'bg-orange-100' },
  seasonal: { label: 'Seasonal', color: 'text-pink-700', bgColor: 'bg-pink-100' },
};

// Frequency display names
export const frequencyConfig: Record<EmailFrequency, { label: string; icon: string }> = {
  'one-time': { label: 'One-time', icon: '1️⃣' },
  daily: { label: 'Daily', icon: '📅' },
  weekly: { label: 'Weekly', icon: '📆' },
  'event-based': { label: 'Event-based', icon: '⚡' },
  annual: { label: 'Annual', icon: '🎉' },
};

// Helper to get emails by category
export function getEmailsByCategory(category: EmailCategory): EmailDefinition[] {
  return emailCatalog.filter(email => email.category === category);
}

// Helper to get personalization stats
export function getPersonalizationStats() {
  const total = emailCatalog.length;
  const personalized = emailCatalog.filter(e => e.isPersonalized).length;
  return {
    total,
    personalized,
    notPersonalized: total - personalized,
    percentage: Math.round((personalized / total) * 100),
  };
}
